### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by FedorSharapov** [Dimonix-mw/OtusHomeWork17#1]
Здравствуйте! Мне понравилась ваша работа, ничего лишнего. Все просто и понятно!

Можно упростить код ниже 
```
T? max = default;
float min = float.MinValue;
foreach (T item in e)
{
    float number = getParameter(item);
    if (number > min)
    {
        max = item;
        min = number;
    }
}
return max;
```
на `return e.MaxBy(x => getParameter(x));`
Я проверил по быстродействию получается одинаково.

**Comment by FedorSharapov** [comment]
Проверил еще раз и получилось что ваша реализация при 10 000 000 итераций быстрее на 100 мс, чем `e.MaxBy`.        Мне подсказали, что `e.MaxBy` медленнее из-за использования IComparer<>.

**Comment by Dimonix-mw** [comment]
Здравствуйте, думаю это не критично 100 мс, хотя зависит от контекста задачи, а читабельнее конечно предложенный Вами вариант, спасибо
